# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=9),
        ),
    ]
