# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171122_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='play',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
